-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versión del servidor:         10.4.11-MariaDB - mariadb.org binary distribution
-- SO del servidor:              Win64
-- HeidiSQL Versión:             12.5.0.6677
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Volcando estructura para tabla ceramicasmarbella.t_clientes
DROP TABLE IF EXISTS `t_clientes`;
CREATE TABLE IF NOT EXISTS `t_clientes` (
  `id_cliente` int(11) NOT NULL AUTO_INCREMENT,
  `id_empresa` int(11) DEFAULT NULL,
  `cliente` varchar(100) DEFAULT NULL,
  `telefono_contacto` varchar(30) DEFAULT NULL,
  `id_estado` int(11) DEFAULT NULL,
  `ciudad` varchar(60) DEFAULT NULL,
  `direccion` varchar(300) DEFAULT NULL,
  `descripcion` text DEFAULT NULL,
  `correo_contacto` varchar(50) DEFAULT NULL,
  `pagina_web` varchar(45) DEFAULT NULL,
  `facebook` varchar(50) DEFAULT NULL,
  `twitter` varchar(50) DEFAULT NULL,
  `instagram` varchar(50) DEFAULT NULL,
  `portada` varchar(150) DEFAULT NULL,
  `id_estatus` int(11) DEFAULT NULL,
  `id_idioma` int(11) DEFAULT NULL,
  `texto_original` int(11) DEFAULT NULL,
  `id_usuario_creador` int(11) DEFAULT NULL,
  `id_usuario_modificador` int(11) DEFAULT NULL,
  `fecha_creacion` datetime DEFAULT NULL,
  `fecha_modificacion` datetime DEFAULT NULL,
  PRIMARY KEY (`id_cliente`),
  KEY `fk_texto_original_t_proveedores_idx` (`texto_original`),
  KEY `fk_m_idiomas_t_proveedores_idx` (`id_idioma`),
  KEY `fk_t_proveedores_s_estatus_idx` (`id_estatus`)
) ENGINE=InnoDB AUTO_INCREMENT=163 DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla ceramicasmarbella.t_clientes: ~160 rows (aproximadamente)
INSERT INTO `t_clientes` (`id_cliente`, `id_empresa`, `cliente`, `telefono_contacto`, `id_estado`, `ciudad`, `direccion`, `descripcion`, `correo_contacto`, `pagina_web`, `facebook`, `twitter`, `instagram`, `portada`, `id_estatus`, `id_idioma`, `texto_original`, `id_usuario_creador`, `id_usuario_modificador`, `fecha_creacion`, `fecha_modificacion`) VALUES
	(1, 65, 'CERAMICONI AYACUCHO', '0248 5214456', 2, 'PTO. AYACUCHO', 'CALLE CATANIPO, SECTOR BARRIO CATANIAPA, PTO. AYACUCHO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2, 15, 'INDUSTRIAS DE AISLANTES Y ACERO I.A.A.', '0414 5022459', 3, 'BARCELONA', 'CALLE CONSTANTINO MARADEI, SECTOR 1, LA PONDEROSA, BARCELONA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(3, 48, 'CERAMIKOZ', '0293 4512510', 3, 'CUMANA', 'AV. LAS INDUSTRIAS, CONGLOMERADO IND. MELANIA CANELONES (ZONA INDUSTRIAL SAN LUIS). CUMANA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(4, 55, 'PURACEMAMICA', '0414 2921967', 3, 'BARCELONA', 'AV. RAUL LEONI, EDIF. PURACERAMICA, PB. SECTOR IND. LOS MONTONES, BARCELONA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(5, 59, 'DISTRIBUIDORA CERAMICA', '0414 8446880', 3, 'BARCELONA', 'Av. Jorge Rodríguez. CC. Vittoria Center, PB, Local 1. Sector Colinas del Neverí, Barcelona', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 69, 'CORPORACION VIDOSO', '0281 2774020', 3, 'BARCELONA', '1ra. Av., ZONA INDUSTRIAL LOS MONTONES, Nro. 195. BARCELONA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 16, 'SUPER LIDER CAGUA', '0414  450 75 49', 5, 'TURMERO', 'Carretera NACIONAL, LA ENCRICIJADA, TURMERO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(8, 30, 'MIGO VICTORIA', '0244 3213777', 5, 'LA VICTORIA', 'CALLE PAEZ ESTE, EDIF. MIGO N° 143-3, URB LAS MERCEDES, LA VICTORIA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 33, 'MIGO TEJERIAS', '0244 3343131 / 3341710', 5, 'TEJERIAS', 'CARRETERA PANAMERICANA, SECTOR LA PRADERA, LAS TEJERIAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 34, 'MIGO PALONEGRO', '0243 2002500', 5, 'PALO NEGRO', 'CARRETERA PALO NEGRO VÍA MAGDALENO, GALPÓN A, CENTRO COMERCIAL SUPER LÍDER, PALO NEGRO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(11, 39, 'HYPERCERAMICA', '0243 2357478', 5, 'MARACAY', 'AV. LOS CEDROS NRO. 154, EDIF. PROSEIN, MARACAY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(12, 45, 'CERAMICAS PRECIO DE FABRICA', '0243 2357478', 5, 'MARACAY', 'Av. Los Cedros, N° 154, Edf. Prosein. Maracay', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(13, 49, 'CITY CERAMICAS', '0243 2695297/ 2692 64', 5, 'TURMERO', 'AV. INTERCOMUNAL TURMERO, LOCAL N° 26, SECTOR LA PROVIDENCIA. TURMERO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(14, 61, 'DOMOSA DECORACIONES', '0414 7894553', 6, 'BARINAS', 'CARRETERA NACIONAL, GALPON CADELMA, SECTOR LOS GUASIMITOS, DTTO. LOS OBISPOS, BARINAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(15, 62, 'DECORACION CERAMICA', '0414 7894553', 6, 'BARINAS', 'AV. INDUSTRIAL, LOCAL DECOCECA, PB. SECTOR LA INDUSTRIAL. BARINAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(16, 63, 'CADELMA BARINAS', '0414 7894553', 6, 'BARINAS', 'AV. 23 DE ENERO, PARCELA 182 Y 183 URB. LA FLORESTA, BARINAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(17, 14, 'MUNDO CERAMICO PRINCIPAL', '0286 9342790/ 9344352', 7, 'SAN FELIX', 'AV. MANUEL PIAR, SECTOR 1ro. DE MAYO, SAN FELIX', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(18, 42, 'PROSEIN', '0285 6323613', 7, 'CIUDAD BOLIVAR', 'SECTOR PLAZA, PASEO MORENO DE MENDOZA, EDIF. EL MINERO, LOCAL 2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(19, 3, 'CERAMIOFERTA', '0424 4303269', 8, 'VALENCIA', 'AV. LISANDRO ALVARADO, GALPON 3 Y 4, N° 105-101. ZONA INDUSTRIAL GUACAMAYA, VALENCIA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(20, 4, 'INSUMACA HOGAR', '0424 4303269', 8, 'VALENCIA', 'AV. LISANDRO ALVARADO, LOCAL N° 119-121, URB. IND. LA GUACAMAYA, VALENCIA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(21, 18, 'FERRETERIA EPA', '0241 8582833', 8, 'VALENCIA', 'AV. USLAR C/C MICHELENA N° 89-72 URB. MICHELENA. VALENCIA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(22, 47, 'ARCOSAN VALENCIA', '0424 4566375', 8, 'NAGUANAGUA', 'CALLEJON MOÑONGO, LOCAL N° 164-186, SECTOR MOÑONGO, NAGUANAGUA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(23, 67, 'MIGO SAN DIEGO', '0251 2667366', 8, 'VALENCIA', 'AV. INTERCOMUNAL DON JULIO CENTENO, CC HIPERLIDER, LOCAL No D-1, SAN DIEGO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(24, 25, 'TABOADA HERMANOS', '0212 4622580', 1, 'CARACAS', 'AV. SAN MARTIN, CASA N°323. CARACAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(25, 43, 'VENEMATERIALES', '0212 8700042', 1, 'CARACAS', 'CALLE PANAMERICANA, ENTRE CHILE Y BOLIVAR, GALPON No 30 CATIA, CARACAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(26, 60, 'COMERCIAL CERAMIGANGA II', '0212 4626849', 1, 'CARACAS', 'Av. San Martín, esquina Alcabala a Palo Grande. Local 07-19. Caracas', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(27, 26, 'CERAMICAS IMPORTADAS FALCON', '0269 2468312', 11, 'PUNTO FIJO', 'Av. FCO. DE MIRANDA, EDIF. Prosein, parcelamiento el jardin. Punto Fijo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(28, 5, 'ARTIFUEGO', '0251 269.15.35', 13, 'BARQUISIMETO', 'CARRERA A1, ENTRE CALLES A2 Y A3, PARCELA N° 48-4. ZONA INDUSTRIAL II, BARQUISIMETO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(29, 6, 'CELOSIAS SPAIN- VEN', '0251 2373907', 13, 'BARQUISIMETO', 'CARRERA 5, esq. Calle 27, zona industrial 1, Barquisimeto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(30, 8, 'MATERIALES LIFECA', '0252 4210180', 13, 'CARORA', 'Calle Bolívar, entre Callejón Salamanca y Callle Jose Luis Andrade. Sector Centro, Carora', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(31, 13, 'VICTOR JOSE RODRIGUEZ C. A.', '0251 2692758/ 2692171', 13, 'BARQUISIMETO', 'CALLE 41, ENTRE CARRERA 29 Y 30, N°29- 49, SECTOR CENTRO OESTE, BARQUISIMETO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(32, 17, 'PLYPLAST 2004', '0424 5380352', 13, 'QUIBOR', 'CARRETERA KM 11, QUIBOR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(33, 19, 'PROCERAMIC', '0251 2319110', 13, 'BARQUISIMETO', 'Carrera 23, Esquina Calle 31, N. 30-116. Sector Centro. Barquisimeto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(34, 24, 'AGENCIA ROYAL 33', '0251 2329080', 13, 'BARQUISIMETO', 'Av. 20, Esquina Calle 33, Local 32-76, Sector Centro, Barquisimeto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(35, 31, 'MIGO LARA', '0251 4451423', 13, 'BARQUISIMETO', 'ZONA IND. 1, CALLE 7, CARRERA 4 Y AV. LIBERTADOR, BARQUISIMETO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(36, 32, 'MIGO LARA II', '0251 2667366', 13, 'BARQUISIMETO', 'AV. FLORENCIO JIMENEZ, ENTRE CALLE 4 Y 6 (AL LADO DE ESTC. TAMUNANGUE), PUEBLO NUEVO, BARQUISIMETO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(37, 36, 'PRECA', '0251 4201000', 13, 'BARQUISIMETO', 'AV. FERROCARIL CON CARRERA 3, EDIF. PROSIDER. ZONA INDUSTRIAL COMDIBAR I. BARQUISIMETO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(38, 52, 'FERRE-GRES', '0253 6632596', 13, 'EL TOCUYO', 'CALLE 19, ESQUINA CARRERA 11, SECTOR SANTO DOMINGO. EL TOCUYO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(39, 68, 'BALDOSAS OCCIDENTE', '0414 5032404', 13, 'BARQUISIMETO', 'Carrera 23, entre calles 31 y 32 (diagonal a la iglesia el cristo) edf. baldosas occidente, Barquisimeto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(40, 20, 'FADIMAC', '0275 8815164', 14, 'EL VIGIA', 'URB. LOS PARQUES , CALLE LOS MANGOS , NRO 57 , SECTOR PARAISO, EL VIGIA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(41, 27, 'MIGO TORONDOY', '0271 7721357 / 7721785', 14, 'MERIDA', 'CARRETERA PANAMERICANA, SECTOR SAN RAFAEL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(42, 37, 'MIL CERÁMICAS', '0275 8810922', 14, 'EL VIGIA', 'FINAL AV. BOLIVAR, SECTOR COCO FRIO (VIA STA. BARBARA) , EDIF. MIL CERÁMICAS, EL VIGIA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(43, 50, 'MIL CERÁMICAS', '0414 0823011', 14, 'MERIDA', 'AV. DON TULIO,  NUMERO 30-40. MERIDA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(44, 51, 'CASA CERAMICA', '0414 0823011', 14, 'MERIDA', 'ZONA INDUSTRIAL LOS CUROS, CALLE 1, GALPON A-2. MERIDA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(45, 56, 'CERAMICAS EL VIGIA', '0275 8820115 / 8820600', 14, 'EL VIGIA', 'Av. Don Pepe Rojas, Sector La Creole, Local N° 927-A, El Vigía', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(46, 1, 'MIL CERÁMICAS', '0212 3214717', 15, 'LOS TEQUES', 'AV. WILLIAN TORBAY, SECTOR LA LOMITA, GALPON N. 2. LOS TEQUES', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(47, 35, 'MIGO CHARALLAVE', '0239 2489619', 15, 'CHARALLAVE', 'AV. TRICENTENARIO (AL LADO DE SUPERLIDER), SECTOR MADOSA, CHARALLAVE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(48, 40, 'FORMAS CERAMICAS 9540', '212 3420832', 15, 'GUATIRE', 'AV. VILLA HEROICA, FRENTE A URB. TERRINCA, GALPON PROSEIN, GUATIRE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(49, 41, 'PRODUCTOS CERAMICOS 4040', '0212 3420160', 15, 'GUATIRE', 'AV. VILLA HEROICA, FRENTE A URB. TERRINCA, GALPON PROSEIN, GUATIRE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(50, 58, 'CERAMICAS LA TINAJA', '0212 2581430', 15, 'CARACAS', 'CALLE LA TINAJA, PETARE, CARACAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(51, 53, 'GLOBAL GRES', '0295 2636101', 17, 'PORLAMAR', ' Av. Llano Alto, entre Av. Terranova y Circunvalación, Sector Archipano, Edif. Global Gres. Porlamar', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(52, 7, 'SIRVEN', '0212 8700042', 18, 'GUANARE', 'CARRERA 4, ESQUINA CALLE 19, LOCAL S/N, BARRIO CURAZAO, GUANARE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(53, 64, 'MAQUINARIAS CADELMA ACARIGUA', '0414 7894553', 18, 'ARAURE', 'AV. LOS PIONEROS, EDF. MARGARITA, PB, LOCAL 1. ARAURE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(54, 10, 'CIRO CERAMI', '0414 0750853', 20, 'SAN CRISTOBAL', 'CALLE 10 CON CARRERA 10, EDIF. PRO CONSTRUCCION, SAN CRISTOBAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(55, 23, 'FERRECERAMICAS BELMAR', '0277 7230775', 20, 'EL PIÑAL', 'CALLE PRINCIPAL, NRO 1-74, P.B. HOTEL CHARLES, EL PIÑAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(56, 28, 'MIGO SABANA', '0271 6694312', 21, 'MENDOZA', 'CARRETERA PANAMERICANA, SABANA DE MENDOZA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(57, 38, 'EL MUNDO DE LA CERAMICA', '0271 2311203', 21, 'VALERA', 'AV. 5 CON CALLE 14, EDF. SANTA RITA, LOCAL 2, SECTOR LAS ACACIAS, VALERA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(58, 44, 'INVERSIONES CISA', '0212 3316818', 24, 'MAIQUETIA', 'Calle Real de Montesano, Galpon 8. Maiquetia', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(59, 46, 'MIL CERÁMICAS', '0212 3521088', 24, 'LA GUAIRA', 'AV. LA ARMADA (FRENTE A FARMATODO) SECTOR LA LUCHA. LA GUAIRA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(60, 54, 'CENTRO CERAMICO LITOMAR', '0212 3324860', 24, 'LA GUAIRA', 'CALLE REAL DE MONTESANO, GALPON Nº,5 LA GAUIRA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(61, 57, 'PURACERAMICA LITORAL', '0212 3524205', 24, 'CATIA LA MAR', 'Av. La Armada, Edif. Puraceramica, Catia La Mar', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(62, 12, 'FERRETERIA LA NUEVA ECONOMICA', '0254 5725262', 22, 'NIRGUA', 'Calle 5ta. con Av. 7ma. Nirgua', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(63, 21, 'MATERIALES SANTA LUCIA', '0251 4820558', 22, 'YARITAGUA', 'CALLE CANAL DE SERVICIO NORTE, ENTRE CALLES 8 Y 9, SECTOR SAN JOSE. YARITAGUA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(64, 22, 'CONCRETERA OL-BLO-CO', '0251 8881242', 22, 'YARITAGUA', 'Autopista CIMARRÓN ANDRESOTE, Entrada via Apayare, Local 46, Barrio Nuevo, Sabana de Parra', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(65, 66, 'ACEROS YARACUY', '0254 2343682', 22, 'SAN FELIPE', '2DA. AVENIDA CON CALLE 21, SAN FELIPE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(66, 2, 'CONSTRUCENTRO NUEVA ROSA', '0264 3712858', 23, 'CABIMAS', 'CARRETERA JM. 370 SECTOR NUEVA ROSA. CABIMAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(67, 9, 'DECOINTER', '0424 2485059', 23, 'SANTA CRUZ DE MARA', 'Calle Ppal., Sector Catatumbo Internacional, Santa Cruz de Mara', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(68, 11, 'DECOSERVICES', '0414 7191615', 23, 'MARACAIBO', 'AV. 17, CC ALCHESA, NIVEL PB, GALPON N°2, SECTOR LOS HATICOS, MARACAIBO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(69, 29, 'MIGO LAGO', '0271 7721527/1530', 23, 'CAJA SECA', 'CARRETERA VIA BOBURES, FRENTE AL SECTOR LA CONQUISTA, CAJA SECA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70, 70, 'FERROCERAMICA VALCRO, C. A.', '0241-8358488 / 8610640', 8, 'VALENCIA', 'Autopista Valencia, Campo de Carabobo, galpón B-17, sector el socorro, Valencia, Edo. Carabobo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(71, 71, 'CATALANO HOME CENTER, C.A.', '0295-287.05.51', 17, 'EL VALLE', 'Av. 31 de Julio, Edif. Catalano Home Center, PB. Local 1, Sector Guatamare-García. El Valle, Edo. Nueva Esparta', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(72, 72, 'CERAMICMANIA, C.A.', '0291-286.30.80', 3, 'LECHERIAS', 'Av. Intercomunal, Centro Empresarial Las Garzas, Nivel Pb. Locales 3,4,5 y 6. Sector Las Garzas, Lecherías Edo. Anzoátegui ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(73, 73, 'FERRETERIA CHAPELLIN, C.A', '0212-730.97.12', 1, 'CARACAS', 'Calle Real de Chapellín, Casa Nro. 88, Sector Chapellín, Caracas Dtto. Capital', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(74, 74, 'CERAMICAS LA SANTINA, C.A.', '0412-934.38.53', 1, 'CARACAS', 'Av. San Martin, Entre Albanales y Cruz De La Vega, Casa N° 284, Caracas Dtto. Capital', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(75, 75, 'DECOCERAMICA EL VIGIA, C.A.', '0275-881.69.35', 14, 'EL VIGIA', 'Av. 15 Núm. 9-3. Sector La Inmaculada, El Vigía, Edo. Mérida', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(76, 76, 'SIMPOLO, C.A.', '0243-269.11.11', 5, 'TURMERO', 'Av. Intercomunal Santiago Mariño, CC Parcela, N.38 Nivel 1, Ofic.1. Sector La Providencia, Turmero Edo. Aragua', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(77, 77, 'INVERSIONES PROCORA IMPORT, C.A.', '0291-643.92.75', 16, 'MATURIN', 'Av. Alirio Ugarte Pelayo, Galpón N.47, Sector Bajo Guarapiche. Maturín Edo. Monagas', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(78, 78, 'CENTRO CERAMICO GARCIA I, C.A.', '0212-481.49.80', 1, 'CARACAS', 'Av. San MartÍn, entre Albanales y Cruz De la Vega, Casa N° 284. Caracas Dtto. Capital', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(79, 79, 'CENTRO CERAMICO LA FUERTE, C.A.', '0424 928.08.97', 7, 'PUERTO ORDAZ', 'Av. Principal De Castillito, frente a la Bomba PDV. Puerto Ordaz, Edo. Bolívar', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(80, 80, 'BALDOZULIA, C.A.', '0414 - 526.37.01', 23, 'MARACAIBO', 'Calle 82 Local No 2-B, Conjunto Residencial Doña Paula, Sector Belloso. Maracaibo, Edo. Zulia', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(82, 82, 'INVERSIONES ROSDANY, C.A.', '0283 - 241.63.95/14.80', 3, 'EL TIGRE', '3ra. Carrera Sur, entre Calles 23 y 24 Edif. Los Chaguaramos, PB. Sector Pueblo Nuevo. El Tigre Edo. Anzoátegui.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(83, 83, 'DECOSANITARIOS, C.A.', '0414-745.50.23', 14, 'MERIDA', 'Carretera Panamericana, Sector El Llano del Anís -entrada Chiguará- Mérida,  Edo. Mérida', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(84, 84, 'CERAMICAS Y REVESTIMIENTOS, C.A.', '0416-502.24.31', 21, 'VALERA', 'Av. Independencia, Sector Plata, Galpón 1. Valera, Edo. Trujillo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(85, 85, 'BALDOLARA, C.A.', '0251-253.60.32', 13, 'BARQUISIMETO', 'Carrera 7, entre Av. Lara y Carrera 1, Urb. Nueva Segovia, Barquisimeto Edo. Lara', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(86, 86, 'DISTRIBUIDORA MULTIMAT, C.A.', '0244-995.40.13', 5, 'LA VICTORIA', 'Calle B, Parcela 8, Zona Industrial 2121. La Victoria, Edo. Aragua', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(87, 87, 'CENTRO CERAMICA TREBOL, C.A.', '0243-234.01.24', 5, 'MARACAY', 'Av. Los Cedros, c/c calle caldas, No 22 -diagonal a la prefectura Crespo- sector Santa Ana. Maracay. Edo. Aragua', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(88, 88, 'CONSTRU CERAMICA LOS CEDROS, C.A.', '0414-345.65.85', 5, 'MARACAY', 'Av. Los Cedros, Local N°49, Sector Libertad. Maracay, Edo. Aragua', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90, 90, 'EL GALPON DE LA CERAMICA, C.A', '0414-210.84.21', 15, 'SAN ANTONIO DE LOS ALTOS', 'Av. Las Industrias, Galpón de la Cerámica, zona industrial Las Minas, San Antonio de Los Altos, Edo. Miranda.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(91, 91, 'BALDORUSTICOS, C.A.', '0414-522.33.47', 13, 'BARQUISIMETO', 'Av. Carabobo con Esq. Calle 25. Barquisimeto, Edo. Lara', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(92, 92, 'EL PALACIO DEL CAICO, C. A.', '0264 -371.80.96', 23, 'CABIMAS', 'Av. 32 con Calle San Luis, Local N° 01, Sector Democracia. Cabimas, Edo. Zulia', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(93, 93, 'DECOARTE HOGAR, C.A.', '0414-374.68.73', 14, 'TOVAR', 'Av. Ppal. El Llano, Carrera 4ta., Res. Las Galerías, N° 01. Sector El Llano. Tovar, Edo. Mérida', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(94, 94, 'MATERIALES DE CONSTRUCCION BRAHERCA III, C. A.', '0424-116.65.78', 15, 'SANTA TERESA DEL TUY', 'Carretera Sta. Teresa - Sta Lucia,  Edf. Mil Cerámicas, PB. Local A y A1, Urb. Sta Teresa del Tuy,  Edo. Miranda', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(95, 95, 'BALDOCERAMIC, C.A.', '0251-273.12.22', 13, 'BARQUISIMETO', 'Av. Carabobo, Esquina Carrera 33. Barquisimeto Edo. Lara', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(96, 96, 'BALDOCENTRO, C.A.', '0414-955.38.97', 13, 'BARQUISIMETO', 'Av. Carabobo, entre carrera 33 y 24, Centro. Barquisimeto , Edo. Lara.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(97, 97, 'CONSTRU HOGAR ZONA SUR, C.A.', '0414-796.84.66', 3, 'EL TIGRE', 'Av. Intercomunal, Galpón N°3, Sector Intercomunal El Tigre, Edo. Anzoátegui', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(98, 98, 'CERAMIC PLAZA, C.A.', '0414-789.88.76', 17, 'PORLAMAR', 'Redoma de Los Robles. Porlamar Edo. Nueva Esparta', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(99, NULL, 'Cerámicas la Tinaja', NULL, 15, 'Caracas', 'Av. Tamanaco, Edf. Esma, PB, local 20. El llanito, Petare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(100, NULL, 'Cerámicas Rustriestrella', NULL, 1, 'Caracas', 'Av. Avila, Qta. Trébol, Nº 9. San Bernardino', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(101, NULL, 'Inversiones Mastergres', NULL, 1, 'Caracas', 'Av. Nueva Granada, calle Branger, local C. Santa Rosalia', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(102, NULL, 'Inversiones GTM', NULL, 15, 'Caracas', 'Carretera Petare-Guarenas, km 13. Caucaguita', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(103, NULL, 'Inversiones Ferre Gama 1ra.', NULL, 1, 'Caracas', 'Calle Sur 8, entre esq. Cruz de la Vega y Palo Grande, San Martín', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(104, NULL, 'Importadora Deko Styl 101', NULL, 15, 'Caracas', 'Av Ernesto Blohm, CCCT, 1era. etapa, local L843-1. Chuao', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(105, NULL, 'El galpón cerámico', NULL, 15, 'Caracas', 'Carretera vieja Caracas-Las Minas, sector los mangos, galpón b-4, Minas de Baruta', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(106, NULL, 'Grupo Metrocuadrado', NULL, 15, 'Caracas', 'Av Ernesto Blohm, CCCT, Chuao', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(107, NULL, 'Materiales y Cerámicas Elicardo', NULL, 1, 'Caracas', 'Av. San Martín, edif. Valle Alto, PB, local 1, Zona Cruz de la Vega', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(108, NULL, 'Cerámica Carapa', NULL, 1, 'Caracas', 'Calle intermedia, c/c Conde Tovar, Parcelamiento n°5, La Yaguara', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(109, NULL, 'Comercializadora CIMA 261', NULL, 1, 'Caracas', 'Calle Panamericana, entre Chile y Bolivia, casa Nº 2845, Catia', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(110, NULL, 'Distribuidora Maracaná', NULL, 1, 'Caracas', 'Esq. de Alcabala a Peligro, local Nº3, La candelaria', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(111, NULL, 'Servicios M.R.E 2004', NULL, 15, 'Caracas', 'Final Av. Ppal. El Cafetal, local Nº17, Los Naranjos', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(112, NULL, 'Venemateriales', NULL, 1, 'Caracas', 'Calle Panamericana entre Chile y Bolivia, galpón n°30, Catia', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(113, NULL, 'Materiales El Arcillero', NULL, 1, 'Caracas', '1era. Av con 2da. Transv., Local N 41, Zona Industrial de Artigas', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(114, NULL, 'Ferretería JDR', NULL, 15, 'Caracas', 'Av. Fco. de Miranda, Local Ferreteria JDR, La California Norte', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(115, NULL, 'Megacerámicas y Algo Más', NULL, 1, 'Caracas', 'Av. Ppal. Entre calle Chile y México, Edif. Orquídea, PB, Nueva Caracas', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(116, NULL, 'Don Gres II', NULL, 3, 'Barcelona', 'Calle Guayaquil, entre Av. Intercomunal Jorge Rdz. y calle Andrés Bello', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(117, NULL, 'Himalaya Baths & Tiles', NULL, 3, 'Barcelona', 'Av. Intercomunal Jorge Rdz., sector Las Garzas -frente a RODOVIAS-', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(118, NULL, 'Inversiones Mármolgres', NULL, 5, 'Maracay', 'Av. Bolívar, CC. Parque Aragua, Local 29, Nivel Sótano', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(119, NULL, 'Centro Cerámico Simonelli', NULL, 5, 'Maracay', 'Av. Los Cedros, Local 245-A, Santa Ana', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(120, NULL, 'Ferre-MaterialesS Pérez F.P.', NULL, 6, 'Barinas', 'Esq. Carrera 6 c/c Calle 3, Casa Nº 6-10, barrio Las Flores, Socopo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(121, NULL, 'Expocerámica Barinas', NULL, 6, 'Barinas', 'Av. Libertad, entre Av. Elias Cordero y Calle Aranjuez, Local 16-58, sector San José', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(122, NULL, 'Inversiones FerreMundo', NULL, 6, 'Barinas', 'Calle Mijagual, Casa Nº 51-58, La Concordia', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(123, NULL, 'Ferremateriales La Fuerte', NULL, 7, 'Puerto Ordaz', 'Av Ppal. de Castillito -local a nivel de calle-', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(124, NULL, 'Femapuerto', NULL, 8, 'Puerto Cabello', 'Vereda H1, Local 01, Urb. Travieso Paul, sector Las Llaves', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(125, NULL, 'Ferre Agro Quibor', NULL, 13, 'Quibor', 'Av. Florencio Jiménez, sector La Ceiba', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(126, NULL, 'Decorústicos Lara', NULL, 13, 'Barquisimeto', 'Carrera 25, Esquina calle 15', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(127, NULL, 'Ferregranito', NULL, 13, 'Barquisimeto', 'Carrera 25 con Calle 41 y  Av. Concorcordia Carrera 8 (detrás del Sambil)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(128, NULL, 'GKO Superficies', NULL, 13, 'Barquisimeto', 'Carrera 25 entre calles 13 y 14, Casa Nº 13-11, sector Centro', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(129, NULL, 'Ferremateriales La Mano de Dios', NULL, 13, 'Carora', 'Calle Gil  Fortoul, entre Av. 14 de Febrero e Isaias Avila, sector Valparaíso', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(130, NULL, 'Porcelara', NULL, 13, 'Barquisimeto', 'Carrera 23, esq. Calle 24, sector Centro', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(131, NULL, 'Materiales El Albañil', NULL, 13, 'Carora', 'Calle 12 con Carretera LARA-ZULIA, zona Ind. de Carora', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(132, NULL, 'Constru Ofertas GH', NULL, 13, 'Barquisimeto', 'Av. Florencio Jiménez, entre calles 4 y 6, sector Pueblo Nuevo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(133, NULL, 'Corporación GP Sinaí', NULL, 13, 'Barquisimeto', 'Carrera 25, entre calles 13 y 14, sector Centro', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(134, NULL, 'Home Deco', NULL, 14, 'Mérida', 'Av. Alfredo Briceño Paredes, Parcela A-2 y A-3, sector Los Curos', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(135, NULL, 'Administradora de Inmuebles', NULL, 14, 'Mérida', 'Av. Don Tulio Febres Cordero, casa Nº 30-40, sector El Llano', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(136, NULL, 'Cerámicas Occidente', NULL, 14, 'El Vigía', 'Av. 15, casa Nº 5-19, sector Barrio Bolívar', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(137, NULL, 'El Galpón de la Cerámica', NULL, 15, 'San Antonio de Los Altos', 'Av. Las Industrias, Zona Industrial Las Minas', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(138, NULL, 'Inversiones Cerámicas Latina', NULL, 15, 'Los Teques', 'Av. Willian Torbay, Galpon Nº 20, La Lomita', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(139, NULL, 'Distribuidora Cerámicas el Tambor', NULL, 15, 'San Antonio de Los Altos', 'Av. Chaid Torbay, Edif Ind. Campestre, Piso 1, Local 1. Sector Industrial Las Minas', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(140, NULL, 'Cerámicas Hatillo Gres', NULL, 15, 'Cua', 'Carretera Charallave Cua, entrada a La Morita, Quebrada de Cua', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(141, NULL, 'Cerámica Italmiranda', NULL, 15, 'Los Teques', 'Calle La Francesa c/c Gillette, C.C. Ripe, PB, Local 1.  Sector El Vigia', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(142, NULL, 'Rústicos y Baldosas siglo XXI', NULL, 15, 'Sta. Teresa del Tuy', 'Calle San Rafael, Local 2B, Centro', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(143, NULL, 'Gricosoluciones', NULL, 15, 'Los Teques', 'Av. Maria Pérez Pisanti, Edif. Gricocerámica, Piso5, Zona Industrial', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(144, NULL, 'Centro Cerámico El Guacharo II', NULL, 16, 'Maturin', 'Av. Bella Vista, local, 1 sector La Muralla', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(145, NULL, 'Inversiones 0905', NULL, 18, 'Araure', 'Calle 5, esquina Av. 31, Zona Industrial de Araure', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(146, NULL, 'Construcerámica Quintero', NULL, 20, 'San Cristóbal', 'Calle 4, entre CR 6 y 7, Casa B-11, Urb. Propatria, sector La Concordia', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(147, NULL, 'Construcerámica Guadalupe', NULL, 20, 'San Cristóbal', 'Calle 4, Local 6-31. Urb Propatria, sector La Concordia', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(148, NULL, 'Materiales Don Pedro', NULL, 20, 'La Fría', 'Carretera Panamericana, Galpón 3-57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(149, NULL, 'Materiales Agromater', NULL, 20, 'Coloncito', 'Carretera Norte Sur, Local Agromater, sector Redoma El Toro', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(150, NULL, 'Porcelanatos y Cerámicas Valera', NULL, 21, 'Valera', 'Av. Bolívar, sector La Plata', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(151, NULL, 'Villacerámica', NULL, 21, 'Valera', 'Av. Bolívar, esq. Calle Mayor, sector La Plata', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(152, NULL, 'El Ofertón de La Cerámica Valera', NULL, 21, 'Valera', 'Calle 7, entre Avenidas 4 y 5, sector Casco Central (diagonal a Café Serra)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(153, NULL, 'Instalcenter', NULL, 22, 'Yaritagua', 'Esq. Calle 15, E.S. PDV Cristal, sector San José de Yatitagua.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(154, NULL, 'Distribuidora Verona 2000', NULL, 23, 'Maracaibo', 'Av. 58 Circunvalación 2, Local 99A-31, Barrio Ixora Rojas', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(155, NULL, 'Rusticerámica', NULL, 23, 'Maracaibo', 'Av. 20, Nº 100 B, Sector Sabaneta, Barrio El Calvario', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(156, NULL, 'Beyond Venezuela', NULL, 23, 'Maracaibo', 'Av. 37, Local 57A-37, Sector Don Bosco', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(157, NULL, 'Inversiones Centro Ceramico Col', NULL, 3, 'Ciudad Ojeda', 'Av. Cristóbal Colón, Local 14, Sector Colonia López', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(158, NULL, 'Cerámicas Tu Solución', NULL, 3, 'Ciudad Ojeda', 'Carretera L, entre Av. 33 y 34, Res. Canaima, PB. sector La L (diag. Licorería Lidisca)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(159, NULL, 'Cerámicas Andrea', NULL, 23, 'Maracaibo', 'Calle 79, Local 53-07, Sector Panamericano', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(160, NULL, 'El Ofertón de La Cerámica La Limpia', NULL, 23, 'Maracaibo', 'Av. La limpia con calle 70, local 43-88, sector La Macandona', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(161, NULL, 'Ferrecerámica La Grande', NULL, 23, 'Maracaibo', 'Calle 95, Casa 61-59, Barrio 1ro. de Agosto, 1era. Etapa de Raúl Leoni', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(162, NULL, 'Cerámicas Don Baratón', NULL, 23, 'Maracaibo', 'Av. 22, Casa Nº 100C-11, Barrio La Sonrisa', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
